name: news
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.2.1
  shimmer: ^3.0.0
  stroke_text: ^0.0.3
  webview_flutter: ^4.8.0

dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/categories/
    - assets/news/

  fonts:
    - family: bebas
      fonts:
        - asset: assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf
    - family: crimson
      fonts:
        - asset: assets/fonts/Crimson_Text/CrimsonText-Regular.ttf
    - family: Abril
      fonts:
        - asset: assets/fonts/Abril_Fatface/AbrilFatface-Regular.ttf
